### ISSUE TITLE
FEAT: 마고는 코디 페이지를 작성해요

### ISSUE THREAD

**Issue by soltihoshi** [How-weather/front#11]
## Description
코디 페이지 작성하기

## To-Do
- [x] 상단바 작업하기
- [x] 코디이미지 캐러셀 적용하기
- [x] 추천아이템 섹션 추가하기
- [x] 추천아이템별 그리드 적용하기

## ETC
마고 화이팅~!
